import { Footer } from "@/components/Footer";
import { HeroBlog } from "@/components/HeroBlog";
import AllBlogs from "@/components/AllBlogs";

export const metadata = {
  title: "WebTo Blog - The ultimate website development agency",
  description: "Generated by create next app",
};

export default function BlogPage() {
  return (
    <>
      <HeroBlog />
      <AllBlogs />
      <Footer />
    </>
  );
}
